#pragma once

struct ProcessData {
	PCWSTR ProcessPath;
	PCWSTR ProcessName;
};

#define PROCESS_GUARD_DEVICE 0x8000

#define IOCTL_PROCESS_GUARD_FORBIDDEN_PROCESS CTL_CODE(PROCESS_GUARD_DEVICE, \
	0x800, METHOD_NEITHER, FILE_ANY_ACCESS)